# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bgreet.proto\x12\x05greet\"\"\n\x0cGreetRequest\x12\x12\n\nfirst_name\x18\x01 \x01(\t\"\x1f\n\rGreetResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2\xfb\x01\n\x0cGreetService\x12\x32\n\x05Greet\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse\x12=\n\x0eGreetManyTimes\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse0\x01\x12\x38\n\tLongGreet\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse(\x01\x12>\n\rGreetEveryone\x12\x13.greet.GreetRequest\x1a\x14.greet.GreetResponse(\x01\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'greet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GREETREQUEST._serialized_start=22
  _GREETREQUEST._serialized_end=56
  _GREETRESPONSE._serialized_start=58
  _GREETRESPONSE._serialized_end=89
  _GREETSERVICE._serialized_start=92
  _GREETSERVICE._serialized_end=343
# @@protoc_insertion_point(module_scope)
